version: '3.4'

services:
    database:
        image: '${REGISTRY_NAME}mongo:4.2-bionic'
        volumes:
            - casidb:/data/db
        networks:
            - 'internal'
        restart: 'unless-stopped'
    redis:
        image: '${REGISTRY_NAME}redis:6.2-alpine'
        restart: always
        networks:
            - 'internal'
        ports:
            - '6379:6379'
        env_file:
            - './.env'
        command: redis-server --loglevel warning --requirepass ${REDIS_PASS}
        volumes:
            - casi_redis:/data
    CASI:
        build: .
        image: '${REGISTRY_NAME}devclubiitd/casi:0.1'
        ports:
            - ${PORT}:${PORT}
        healthcheck:
            test: ['CMD', 'curl', 'http://localhost:${PORT}']
            interval: 1m30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: 'unless-stopped'
        networks:
            - 'internal'
            - 'reverseproxy'
        env_file:
            - ./.env
        environment:
            - VIRTUAL_HOST
            - MONGODB_URI_LOCAL
        depends_on:
            - database
            - redis

volumes:
    casidb:
    casi_redis:

networks:
    reverseproxy:
        external:
            name: 'reverseproxy'
    internal:
